"""ONE figure for the rule-task check: row 1 = the task's symmetry and the predicted wells (scheme) for
each tie; rows 2-3 = simulations (two-sided / one-sided objective): seed-0 flow with the attractors of all
four seeds overlaid, and the equivariance residuals. Columns: free | tied -I | tied diag(+1,-1) | tied group.
Usage: rulesym_summary_fig.py <sweep_dir> <out.png>"""
import sys, os, textwrap, numpy as np, torch, matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt, seaborn as sns
from matplotlib.patches import FancyArrowPatch
sys.path.insert(0, "/home/leon/rnn/scratchpad"); from symtools import *
from src.flow_rank2 import _flow_panel_cache, _render_flow_panel
from bifurcation_probe import find_wells
sns.set_context("notebook"); sns.set_style("ticks"); plt.rc("axes.spines", top=False, right=False)
plt.rcParams.update({"font.size": 11, "mathtext.fontset": "cm", "axes.linewidth": 0.9})
sw, out = sys.argv[1:3]; XL = (-1.5, 1.5)
COLS = [("free", "free\n(no tie)", None), ("tied", "tied to  −I\n(both modes flip)", "s2"), ("dec", "tied to  diag(+1, −1)\n(decision flips, memory kept)", "s3"), ("klein", "tied to the whole group\n(both, 4 blocks)", None)]
ARM = {("afc", "free"): "rulesym_afc", ("afc", "tied"): "rulesym_afc_tied", ("afc", "dec"): "rulesym_afc_dec", ("afc", "klein"): "rulesym_afc_klein",
       ("gng", "free"): "rulesym_gng", ("gng", "tied"): "rulesym_gng_tied", ("gng", "dec"): "rulesym_gng_dec", ("gng", "klein"): "rulesym_gng_klein"}
teal, plum, ember = "#0d818b", "#6b2f74", "#b0460e"
fig = plt.figure(figsize=(17, 14.6), dpi=140); gs = fig.add_gridspec(4, 4, height_ratios=[0.5, 0.85, 1, 1])
# ---------- row 0: the task symmetry, as text ----------
ax = fig.add_subplot(gs[0, :]); ax.axis("off")
W = lambda t: textwrap.fill(t, 175)
ax.text(0.0, 1.0, W("The rule task alone: stimulus go or nogo, delay, cue, respond. Relabeling go ↔ nogo with the response flipped leaves the two-sided task unchanged (it is a Z₂); the one-sided task (go ≥ θ, nogo ≤ 0) is invariant under nothing.") + "\n\n"
        + W("Because the objective never reads κ₀, the relabeling can act on the plane in two ways — both modes flip (D = −I) or the decision alone flips (D = diag(+1, −1)) — and their product flips the memory mode with no relabeling at all: a Klein four-group of parameter symmetries, generated by the two.") + "\n\n"
        + W("Predictions (ring log §38c, refined in §38d): a tie gives the orbits of its group — antipodes under −I, a mirror pair across the line under diag(+1, −1), pairs on the axes under the whole group. Where a pair sits along the invariant direction is not fixed by the group but by the even/odd identity: a mode that the tie copies has a field component on the other mode's axis equal to its readout mean plus a bias term, so that axis is an invariant line when both are small; a mode the tie flips has no such axis. Hence −I: antipodes at a free angle, no invariant axis; diag(+1, −1): the κ₀ axis exactly invariant and the κ₁ axis nearly so, the pair on it; the whole group: both axes invariant, a pair on each (the κ₀ pair belongs to the unused memory mode). J₀₁, J₁₀ are free under −I and 0 under the other two. Every tie learns both tasks."),
        fontsize=10, va="top", family="serif", transform=ax.transAxes, linespacing=1.35)
# ---------- row 1: scheme of predicted wells ----------
def scheme(ax, wells, pairs, title, note):
    ax.set_xlim(-1.4, 1.4); ax.set_ylim(-1.4, 1.4); ax.set_aspect("equal"); ax.axhline(0, color=ember, lw=1.1, ls=(0, (4, 3))); ax.axvline(0, color="0.8", lw=0.8)
    for (x, y) in wells: ax.plot(x, y, "o", color=teal, ms=9, zorder=4)
    for (x0, y0), (x1, y1) in pairs: ax.add_patch(FancyArrowPatch((x0, y0), (x1, y1), arrowstyle="<->", color=plum, lw=1, mutation_scale=10, linestyle=":"))
    ax.set_xticks([]); ax.set_yticks([]); ax.set_title(title, fontsize=10, pad=6); ax.text(0.5, -0.06, note, transform=ax.transAxes, ha="center", va="top", fontsize=8.5, color="0.35")
    ax.set_ylabel("κ₁", fontsize=9); ax.text(0.97, 0.03, "κ₀", transform=ax.transAxes, ha="right", va="bottom", fontsize=9, color="0.4")
a, w = 0.35, 0.85
ax0 = fig.add_subplot(gs[1, 0]); scheme(ax0, [], [], "free: no constraint", "any orbit to the right is allowed;\nthe seed decides which")
ax0.text(0.5, 0.5, "?", transform=ax0.transAxes, ha="center", va="center", fontsize=26, color="0.6")
ax1 = fig.add_subplot(gs[1, 1]); scheme(ax1, [(a, w), (-a, -w)], [((a, w), (-a, -w))], "tied to −I: antipodes", "(a, w) and (−a, −w), angle free —\nno invariant axis; J₀₁, J₁₀ free")
th = np.linspace(0.35, 1.2, 30); ax1.plot(0.92 * np.cos(th), 0.92 * np.sin(th), color="0.6", lw=1, ls=":"); ax1.plot(-0.92 * np.cos(th), -0.92 * np.sin(th), color="0.6", lw=1, ls=":")
ax2 = fig.add_subplot(gs[1, 2]); scheme(ax2, [(0, w), (0, -w)], [((0, w), (0, -w))], "tied to diag(+1, −1): mirror pair", "(a, w) and (a, −w) across the line; the κ₁ axis is\ninvariant up to ⟨n₀⟩ and b, so a ≈ 0; J₀₁ = J₁₀ = 0")
ax2.annotate("", (0.35, 0.0), (-0.35, 0.0), arrowprops=dict(arrowstyle="<->", color="0.55", lw=1)); ax2.text(0.0, 0.1, "a", ha="center", fontsize=9, color="0.45")
ax3 = fig.add_subplot(gs[1, 3]); scheme(ax3, [(0, w), (0, -w)], [((0, w), (0, -w))], "tied to the group: pairs on both axes", "(0, ±w) is the memory; both axes are exactly\ninvariant, and the unused mode keeps (±a, 0)")
for x in (0.85, -0.85): ax3.plot(x, 0, "o", ms=9, mfc="none", mec=teal, mew=1.6, zorder=4)
# ---------- rows 2-3: simulations ----------
MK = ["o", "s", "D", "^"]
for r, (obj, objlab) in enumerate([("afc", "two-sided objective  (go → +θ, nogo → −θ)"), ("gng", "one-sided objective  (go ≥ θ, nogo ≤ 0)")]):
    for c, (key, collab, tied_el) in enumerate(COLS):
        arm = ARM[(obj, key)]; ax = fig.add_subplot(gs[r + 2, c])
        seeds = sorted(int(os.path.basename(d)[1]) for d in __import__("glob").glob(f"{sw}/s?_{arm}") if os.path.exists(f"{d}/naive_s{os.path.basename(d)[1]}_{arm}.pth"))
        if not seeds: ax.text(0.5, 0.5, f"{arm}\n(not run yet)", ha="center", va="center", transform=ax.transAxes); ax.set_xticks([]); ax.set_yticks([]); continue
        m0, cfg = load_run(sw, f"s{seeds[0]}_{arm}", stage="naive", device="cpu"); sig = sig_of(cfg)
        cache, spd = _flow_panel_cache(m0, dict(name="Autonomous", dims=None, conds=[]), cfg["input_size"], torch.zeros(1, 1, cfg["input_size"]), XL, XL, 81, field_input_noise=sig, n_fp_seeds=41, slow_tol=0.06)
        _render_flow_panel(ax, cache, speed_vmax=float(np.percentile(spd, 98)), sim_scattered=False, kappa_traj=None, cond_idx={}, colors={}, xlim=XL, ylim=XL, model=m0)
        ax.axhline(0, color="w", lw=0.9, ls=(0, (5, 4)), alpha=0.9)
        res_all = []; nwells = []
        for s in seeds:
            m, cf = load_run(sw, f"s{s}_{arm}", stage="naive", device="cpu"); F_of, P = field_fn(m, sig); rr = residuals(F_of, disk(21)); res_all.append(rr)
            w_ = [f for f, kd, t in find_wells(m, cf, xlim=2.5, n_seeds=41, noise_sigma=sig, with_eigs=True) if str(kd).lower().startswith(("stable", "attract"))]
            w_ = [f for f in w_ if np.linalg.norm(f) > 0.15]; nwells.append(len(w_))
            if s != seeds[0]:
                for f in w_: ax.plot(f[0], f[1], MK[s % 4], color="w", ms=6, mew=1.2, mfc="none", zorder=6)
        med = {k: np.median([rr[k] for rr in res_all]) for k in ("s1", "s2", "s3")}
        acc = []
        import json
        for l in open(f"{sw}/results.jsonl"):
            rj = json.loads(l)
            if rj["run_id"].endswith(arm) and rj["run_id"].startswith("s"): acc.append(rj["accuracy"]["after_gng"]["gng"])
        ttl = (f"{collab.splitlines()[0]}\nresiduals (median of {len(seeds)}): −I {med['s2']:.2f} · dec {med['s3']:.2f} · mem {med['s1']:.2f}"
               f"\nattractors per seed {nwells} · task {min(acc):.3f}–{max(acc):.3f}")
        ax.set_title(ttl, fontsize=8.2); ax.set_xticks([-1, 0, 1]); ax.set_yticks([-1, 0, 1]); ax.set_xlabel("κ₀", fontsize=9)
        ax.set_ylabel(("κ₁\n" + objlab) if c == 0 else "κ₁", fontsize=9)
        print(arm, "seeds", seeds, "wells", nwells, "res", {k: round(v, 3) for k, v in med.items()}, flush=True)
fig.text(0.5, 0.005, "Flow: seed 0 (input-noise-averaged field; ○ its attractors, × saddles, △ repellers). White □ ◇ △: the attractors of seeds 1–3 of the same arm. Dashed: the lick line. Residual = ‖F(Dκ) − D F(κ)‖/‖F‖ on the disk |κ| ≤ 1.5 for D = −I, diag(+1,−1) (dec), diag(−1,+1) (mem).",
         ha="center", fontsize=8.5, color="0.3")
fig.suptitle("The rule task alone: symmetries, predicted wells, and what free and tied networks do", fontsize=12, y=0.995)
fig.tight_layout(rect=[0, 0.012, 1, 0.985]); fig.savefig(out, bbox_inches="tight"); print("wrote", out)
